services:
  opa:
    environment:
      OPA_LOG_LEVEL: info

  orchestrator:
    image: ghcr.io/${GITHUB_REPOSITORY_LC:-arescoreadmin/arescore-foundry}/orchestrator:latest
    environment:
      NATS_URL: ${STAGING_NATS_URL:-nats://nats:4222}
      MINIO_ENDPOINT: ${STAGING_MINIO_ENDPOINT:-minio:9000}
      MINIO_ACCESS_KEY: ${STAGING_MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${STAGING_MINIO_SECRET_KEY:-minioadmin}

  spawn_service:
    image: ghcr.io/${GITHUB_REPOSITORY_LC:-arescoreadmin/arescore-foundry}/spawn_service:latest
    environment:
      ORCHESTRATOR_URL: ${CONTROL_PLANE_ORCHESTRATOR_URL:-http://orchestrator:8080}

  nats:
    environment:
      NATS_HTTP_PORT: 8222

  ingestors:
    profiles:
      - range-plane

  minio:
    profiles:
      - range-plane

  loki:
    profiles:
      - observability

