server:
  http_listen_port: 3100
storage_config:
  filesystem:
    directory: /loki/chunks
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
limits_config:
  allow_structured_metadata: true
query_range:
  parallelise_shardable_queries: true
