services:
  opa:
    image: openpolicyagent/opa:0.67.0
    command:
    - run
    - --server
    - --log-level=info
    - /policies
    volumes:
    - ../policies:/policies:ro
    ports:
    - 8181:8181
    restart: unless-stopped
    read_only: true
    cap_drop:
    - ALL
    security_opt:
    - no-new-privileges:true
    networks:
    - foundry_net
  orchestrator:
    depends_on:
      opa:
        condition: service_healthy
    networks:
    - foundry_net
networks:
  foundry_net: {}
