services:
  opa:
    image: openpolicyagent/opa:0.67.0
    command: ["run","--server","--log-level=info","/policies"]
    volumes:
      - ../policies:/policies:ro
    ports:
      - "8181:8181"
    # service-level hardening (valid keys here)
    read_only: true
    cap_drop: ["ALL"]
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["CMD","wget","-qO-","http://127.0.0.1:8181/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s
