services:
  frostgatecore:
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - |
          import json,sys,urllib.request as u
          try:
              r=u.urlopen('http://localhost:8001/health', timeout=2)
              sys.exit(0 if json.loads(r.read() or b'{}').get('ok') else 1)
          except Exception:
              sys.exit(1)
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
