services:
  opa:
    image: openpolicyagent/opa:latest
    command:
      - run
      - --server
      - --addr=0.0.0.0:8181
      - /policies
      - /container_policies
    volumes:
      - ./policies:/policies:ro
      - ./_container_policies:/container_policies:ro
    ports:
      - "8181:8181"
