version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/alerts:/etc/prometheus/alerts
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager
    networks:
      - foundry_net
      - appnet

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    volumes:
      - ./prometheus/alertmanager/config.yml:/etc/alertmanager/config.yml
    ports:
      - "9093:9093"
    networks:
      - foundry_net
      - appnet

networks:
  foundry_net:
    external: true
  appnet:
    external: true
