services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - ./prometheus/alerts:/etc/prometheus/alerts:ro
      - prometheus-data:/prometheus
    ports: ["9090:9090"]
    depends_on:
      orchestrator:
        condition: service_healthy
    networks: [appnet]

  alertmanager:
    image: prom/alertmanager:latest
    command: ["--config.file=/etc/alertmanager/config.yml"]
    volumes:
      - ./prometheus/alertmanager/config.yml:/etc/alertmanager/config.yml:ro
      - alertmanager-data:/alertmanager
    ports: ["9093:9093"]
    networks: [appnet]

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Foundry123!
      - GF_USERS_DEFAULT_THEME=light
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports: ["3001:3000"]
    depends_on: [prometheus]
    networks: [appnet]

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
