services:
  orchestrator:
    # reliable restarts + resource hygiene
    networks:
      - foundry_net
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:rw,size=64m,mode=1777
    networks:
      - foundry_net
    security_opt:
      - no-new-privileges:true
    networks:
      - foundry_net
    cap_drop: [ALL]
    # Uvicorn handles signals; this constrains file handles
    ulimits:
      nofile: 65535
    networks:
      - foundry_net
    # rotate logs on host so disks don’t fill
    logging:
      driver: json-file
    networks:
      - foundry_net
      options:
        max-size: "10m"
    networks:
      - foundry_net
        max-file: "5"
    # (optional) keep-alives short so dead clients free quickly
    environment:
      - UVICORN_TIMEOUT_KEEP_ALIVE=5
    networks:
      - foundry_net

  frontend:
    restart: unless-stopped
    networks:
      - foundry_net
    # nginx needs a couple writable dirs; keep root fs read-only
    read_only: true
    tmpfs:
      - /var/cache/nginx:rw,size=128m,mode=0755
    networks:
      - foundry_net
      - /var/run:rw,size=16m,mode=0755
    security_opt:
      - no-new-privileges:true
    networks:
      - foundry_net
    cap_drop: [ALL]
    ulimits:
      nofile: 65535
    networks:
      - foundry_net
    logging:
      driver: json-file
    networks:
      - foundry_net
      options:
        max-size: "10m"
    networks:
      - foundry_net
        max-file: "5"

networks:
  foundry_net:
    external: true
