services:
  frontend:
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]

  orchestrator:
    read_only: true
    tmpfs: [/tmp]
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]

  log_indexer:
    read_only: true
    tmpfs: [/tmp]
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
