services:
  frontend:
    healthcheck:
      # Try curl first, fallback to wget
      test: ["CMD-SHELL", "(curl -fsS http://localhost:8080/ready || wget -qO- http://localhost:8080/ready) >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  orchestrator:
    healthcheck:
      # Keep Python-based HTTP check (python is guaranteed in this image)
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request,socket; socket.setdefaulttimeout(2); urllib.request.urlopen('http://localhost:8000/health'); sys.exit(0)\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  log_indexer:
    healthcheck:
      # Prefer HTTP /health if present, else succeed on open TCP 8080
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request,socket; socket.setdefaulttimeout(2); \
import urllib.error; \
import urllib.request; \
try: urllib.request.urlopen('http://localhost:8080/health'); sys.exit(0) \
except Exception: s=socket.socket(); s.settimeout(2); s.connect(('localhost',8080)); s.close(); sys.exit(0)\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
