name: infra

services:
  orchestrator:
    build:
      context: ../backend/orchestrator
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=orchestrator
    ports:
      - "8000:8000"
    healthcheck:
      test:
        - CMD
        - python3
        - -c
        - |
          import sys, socket, urllib.request
          socket.setinfra_appnettimeout(2)
          for path in ("/_healthz", "/health"):
              try:
                  r = urllib.request.urlopen(f"http://127.0.0.1:8000{path}")
                  code = getattr(r, "status", getattr(r, "code", 200))
                  if 200 <= code < 400:
                      sys.exit(0)
              except Exception:
                  pass
          sys.exit(1)
      interval: 5s
      timeout: 3s
      start_period: 10s
      retries: 12
    networks:
      infra_appnet:
  infra_appnet:
    name: infra_appnet
    driver: bridge
    attachable: true
    labels:
      tier: infrastructure
      purpose: observability
 [infra_appnet]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: http://orchestrator:8000
    depends_on:
      orchestrator:
        condition: service_healthy
    ports:
      - "3000:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      infra_appnet:
  infra_appnet:
    name: infra_appnet
    driver: bridge
    attachable: true
    labels:
      tier: infrastructure
      purpose: observability
 [infra_appnet]

networks:
      infra_appnet:
  infra_appnet:
    name: infra_appnet
    driver: bridge
    attachable: true
    labels:
      tier: infrastructure
      purpose: observability

  infra_appnet:
    driver: bridge
