services:
  orchestrator:
    build:
      context: ../orchestrator
      dockerfile: Dockerfile
    image: local/ares-orchestrator:dev
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
