services:
  frontend:
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    cap_drop:
      - ALL

  orchestrator:
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL

  log_indexer:
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
