services:
  frontend:
    healthcheck:
      test: ["CMD-SHELL", "(curl -fsS http://localhost:8080/ready || wget -qO- http://localhost:8080/ready) >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 10s

  orchestrator:
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request,socket; socket.setdefaulttimeout(2); urllib.request.urlopen('http://localhost:8000/health'); sys.exit(0)\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  log_indexer:
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request,socket; socket.setdefaulttimeout(2); urllib.request.urlopen('http://localhost:8080/health'); sys.exit(0)\" || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s
