[project]
name = "sentinelcore"
version = "0.0.0"

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["Tests*", "tests*"]
