route:
  receiver: 'slack'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        api_url: ${SLACK_WEBHOOK_URL}
        channel: '#alerts'
