global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml
  - /etc/prometheus/alerts/*.yml

scrape_configs:
  - job_name: 'orchestrator'
    metrics_path: /metrics
    static_configs:
      - targets: ['orchestrator:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
