# At top-level
env:
  GHCR_OWNER: ${{ github.repository_owner }}
name: Build & Push Containers
on: [push, pull_request]

permissions:
  contents: read
  packages: write

jobs:
  guardrails:
    name: Codex Guardrails
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Guardrails
        run: echo "Guardrails OK"

  build_push:
    name: Build & Push Containers
    runs-on: ubuntu-latest
    needs: guardrails
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show workspace and Dockerfile
        run: |
          set -euo pipefail
          # your checks...
          pwd
          ls -al .
          echo "infra/"; ls -al infra || true
          echo "::group::Dockerfile"
          sed -n '1,200p' infra/sentinelcore.Dockerfile || true
          echo "::endgroup::"

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PR) or Build+Push (push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/sentinelcore.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner || 'arescoreadmin' }}/sentinelcore:pr-${{ github.event.number || 'manual' }}

