# .github/workflows/build-and-push.yml
name: Build & Push Containers
on: [push, pull_request]

permissions:
  contents: read
  packages: write

# Force a lowercase owner once, then reuse it
env:
  GHCR_OWNER_LC: ${{ toLower(github.repository_owner) }}
  IMAGE_TAG: ghcr.io/${{ toLower(github.repository_owner) }}/sentinelcore:pr-${{ github.event.number || 'manual' }}

jobs:
  guardrails:
    name: Codex Guardrails
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Guardrails
        run: echo "Guardrails OK"

  build_push:
    name: Build & Push Containers
    runs-on: ubuntu-latest
    needs: guardrails
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show resolved tag (paranoia check)
        run: |
          echo "GHCR_OWNER=${{ github.repository_owner }}"
          echo "GHCR_OWNER_LC=${{ env.GHCR_OWNER_LC }}"
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PR) or Build+Push (push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/sentinelcore.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.IMAGE_TAG }}
