name: Build & Push Containers
on: [push, pull_request]

permissions:
  contents: read
  packages: write

jobs:
  Codex Guardrails:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      # Put any guardrail checks here. Minimal = pass.
      - name: Guardrails
        run: echo "Guardrails OK"

  Build & Push Containers:
    runs-on: ubuntu-latest
    needs: Codex Guardrails
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Login only on push to default branch; PRs build but do not push
      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PR) or Build+Push (push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/sentinelcore.Dockerfile
          push: ${{ github.event_name == 'push' }}
          # Tag is arbitrary on PRs; on push you can add more tags later
          tags: ghcr.io/Arescoreadmin/sentinelcore:pr-${{ github.event.number || 'manual' }}
