name: Build & Push Containers
on: [push, pull_request]

permissions:
  contents: read
  packages: write

jobs:
  guardrails:
    name: Codex Guardrails
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Guardrails
        run: echo "Guardrails OK"

  build_push:
    name: Build & Push Containers
    runs-on: ubuntu-latest
    needs: guardrails
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show workspace and Dockerfile
        run: |
          set -euo pipefail
          pwd
          ls -al .
          echo "infra/"; ls -al infra || true
          echo "::group::Dockerfile"
          sed -n '1,120p' infra/sentinelcore.Dockerfile || true
          echo "::endgroup::"

      # Compute a guaranteed-lowercase owner and a single tag string
      - name: Compute image tag
        id: tag
        shell: bash
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          PRNUM="${{ github.event.number }}"
          if [ -z "$PRNUM" ] || [ "$PRNUM" = "0" ]; then PRNUM="manual"; fi
          IMAGE_TAG="ghcr.io/${OWNER_LOWER}/sentinelcore:pr-${PRNUM}"
          echo "IMAGE_TAG=${IMAGE_TAG}" | tee -a "$GITHUB_ENV"
          # hard fail if anything uppercase sneaks in
          if [ "$IMAGE_TAG" != "$(echo "$IMAGE_TAG" | tr '[:upper:]' '[:lower:]')" ]; then
            echo "Tag is not lowercase: $IMAGE_TAG" >&2
            exit 1
          fi

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PR) or Build+Push (push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/sentinelcore.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.IMAGE_TAG }}
