name: Sentinelcore CI Smoke
on:
  pull_request:
    paths:
      - "backend/sentinelcore/**"
      - "infra/**"
      - "scripts/**"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare env
        run: |
          [[ -f .env.example ]] && cp .env.example .env || echo "VITE_API_BASE=http://localhost:8000" > .env
          [[ -f infra/.env.example ]] && cp infra/.env.example infra/.env || mkdir -p infra && : > infra/.env
      - name: Build & start sentinelcore
        run: docker compose -f infra/docker-compose.yml up -d --build --force-recreate --no-deps sentinelcore
      - name: Wait for healthy
        run: |
          set -e
          for i in {1..60}; do
            s=$(docker inspect -f '{{.State.Health.Status}}' sentinelcore 2>/dev/null || echo "unknown")
            if [ "$s" = "healthy" ]; then exit 0; fi
            sleep 2
          done
          docker ps; docker logs --tail=200 sentinelcore; exit 1
      - name: Hit /health
        run: curl -sf http://localhost:8001/health | jq .
      - name: Smoke /dev/embed and /dev/q
        run: |
          curl -sf -X POST http://localhost:8001/dev/embed -H "content-type: application/json" -d '{"text":"hello cache"}' | jq .
          curl -sf "http://localhost:8001/dev/q?q=ping&k=3" | jq .
          curl -sf -X POST http://localhost:8001/dev/embed -H "content-type: application/json" -d '{"text":"hello cache"}' | jq .
          curl -sf "http://localhost:8001/dev/q?q=ping&k=3" | jq .
