name: Build & Push Containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: build-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codex-guardrails:
    name: Codex Guardrails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint compose
        run: docker compose -f infra/docker-compose.yml config >/dev/null

  build-and-push:
    name: Build, Smoke, Push
    runs-on: ubuntu-latest
    needs: codex-guardrails
    steps:
      - uses: actions/checkout@v4

      - name: Prepare env files for CI
        run: |
          if [ -f .env.example ]; then
            cp .env.example .env
          else
            echo 'VITE_API_BASE=http://localhost:8000' > .env
          fi
          if [ -f infra/.env.example ]; then
            cp infra/.env.example infra/.env
          else
            mkdir -p infra && : > infra/.env
          fi
          docker compose -f infra/docker-compose.yml config >/dev/null

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build + bring up
        run: |
          docker version
          make up

      - name: Smoke
        run: make smoke

      - name: Tear down
        if: always()
        run: |
          [ -f infra/.env ] || (mkdir -p infra && : > infra/.env)
          [ -f .env ] || : > .env
          make down || docker compose -f infra/docker-compose.yml down -v || true

      - name: Push sentinelcore image (if present)
        if: ${{ hashFiles('infra/sentinelcore.Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/sentinelcore.Dockerfile
