name: build-and-smoke
on:
  push:
    branches: [ main, feat/**, chore/** ]
  pull_request:
jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build images
        run: docker compose -f infra/docker-compose.yml build
      - name: Lint yaml (cheap sanity)
        run: docker compose -f infra/docker-compose.yml config >/dev/null
