# .github/workflows/compose-build.yml
name: Build & Push Containers

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  codex-guardrails:
    name: Codex Guardrails
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install PyYAML
        run: python -m pip install --upgrade pip PyYAML
      - name: Check codex.yml policy
        run: scripts/check_codex_guardrails.py

  build-and-push:
    name: Build & Push Containers
    runs-on: ubuntu-latest
    needs: codex-guardrails
    steps:
      - uses: actions/checkout@v4

      - name: Prepare env files for CI
        run: |
          # root .env (frontend expects VITE_API_BASE); use example if present
          if [ -f .env.example ]; then
            cp .env.example .env
          else
            echo 'VITE_API_BASE=http://localhost:8000' > .env
          fi

          # infra/.env from example (you already have infra/.env.example)
          if [ -f infra/.env.example ]; then
            cp infra/.env.example infra/.env
          else
            mkdir -p infra && : > infra/.env
          fi

          # fail fast if compose still references something missing
          docker compose -f infra/docker-compose.yml config >/dev/null

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build + bring up
        run: |
          docker version
          make up

      - name: Smoke
        run: make smoke

      - name: Tear down
        if: always()
        run: |
          # be defensive in teardown too, in case earlier step bailed
          [ -f infra/.env ] || (mkdir -p infra && : > infra/.env)
          [ -f .env ] || : > .env
          make down || docker compose -f infra/docker-compose.yml down -v || true

  spawn-smoke:
    name: Spawn Service Smoke
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Check if spawn_service exists
        id: has_spawn
        run: |
          if grep -q 'spawn_service' infra/docker-compose.yml; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Bring stack up (for spawn)
        if: steps.has_spawn.outputs.present == 'true'
        run: make up

      - name: Exercise spawn endpoint
        if: steps.has_spawn.outputs.present == 'true'
        run: |
          curl -fsS --retry 20 --retry-all-errors --retry-delay 1 \
            -X POST http://localhost:8082/api/spawn \
            -H 'content-type: application/json' \
            -d '{"track":"netplus"}' | tee spawn_response.json

      - name: Tear down
        if: always() && steps.has_spawn.outputs.present == 'true'
        run: |
          make down || docker compose -f infra/docker-compose.yml down -v || true
