name: Build & Push Containers
on:
  push: { branches: [main] }
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions: { contents: read, packages: write }
env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc:
          - { name: log_indexer,        path: log_indexer }
          - { name: orchestrator,       path: orchestrator }
          - { name: sentinelcore,       path: sentinelcore }
          - { name: sentinelred,        path: sentinelred }
          - { name: mutation_engine,    path: mutation_engine }
          - { name: behavior_analytics, path: behavior_analytics }
          - { name: frontend,           path: frontend }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_PREFIX }}-${{ matrix.svc.name }}
          tags: |
            type=raw,value=latest
            type=sha
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
